### ISSUE TITLE
Firefox doesn't support ManifestV3

### ISSUE THREAD

**Issue by tuxPT** [jtsimoes/paco-ua-extension#1]
Firefox doesn't support ManifestV3, can you rollback to V2 ?

**Comment by jtsimoes** [comment]
Thanks for pointing this out.
Although the extension is not focused on the Firefox browser, I thought it was important to fix this _for now_.

[In January 2023, Chrome browser will no longer run Manifest V2 extensions.](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) Let's hope that Firefox will have implemented support for V3 by then.

Either way, it should be fixed now, with the last commit (cef3918c1eec5d6e12e62c82d29f46bf60746f81)
